// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_QFRbKGMt2-92_HGajPlNlOVLHV5k73c',
    appId: '1:706252569810:web:8ed02f8a673f6151bd010b',
    messagingSenderId: '706252569810',
    projectId: 'uok-events-firebase',
    authDomain: 'uok-events-firebase.firebaseapp.com',
    storageBucket: 'uok-events-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWwXJfLtiuDEhdpruYZ3Jy26vXmc870Mo',
    appId: '1:706252569810:android:623cba9652f0046dbd010b',
    messagingSenderId: '706252569810',
    projectId: 'uok-events-firebase',
    storageBucket: 'uok-events-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhZxnwWxdJXYq0OIogJ5BHJAz4BMCAt1U',
    appId: '1:706252569810:ios:1725c76855f33fa5bd010b',
    messagingSenderId: '706252569810',
    projectId: 'uok-events-firebase',
    storageBucket: 'uok-events-firebase.firebasestorage.app',
    iosBundleId: 'com.rosa.uokevents.uokEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhZxnwWxdJXYq0OIogJ5BHJAz4BMCAt1U',
    appId: '1:706252569810:ios:1725c76855f33fa5bd010b',
    messagingSenderId: '706252569810',
    projectId: 'uok-events-firebase',
    storageBucket: 'uok-events-firebase.firebasestorage.app',
    iosBundleId: 'com.rosa.uokevents.uokEvents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_QFRbKGMt2-92_HGajPlNlOVLHV5k73c',
    appId: '1:706252569810:web:b18c9a18422258adbd010b',
    messagingSenderId: '706252569810',
    projectId: 'uok-events-firebase',
    authDomain: 'uok-events-firebase.firebaseapp.com',
    storageBucket: 'uok-events-firebase.firebasestorage.app',
  );

}